apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dy7aw9e42-java-quarkus 
  janus-idp.io/tekton: dy7aw9e42-java-quarkus
  backstage.io/kubernetes-id: dy7aw9e42-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dy7aw9e42-java-quarkus
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml